name: Docker Register Oracle Service

runs:
  using: 'composite'
  
  steps:
    - name: Register Oracle Service
      shell: pwsh
      run: |
        # Script (Register Oracle Service)
        # Define the Docker container name
        $containerName = "oracle-db"

        # Function to execute a SQL command inside the Docker container
        function Exec-SqlInContainer {
            param (
                [string]$containerName,
                [string]$sqlCommand
            )
            $escapedSqlCommand = $sqlCommand -replace '"', '\"'
            $command = "docker exec $containerName sqlplus / as sysdba -S -L -c `"$escapedSqlCommand`""
            Invoke-Expression $command
        }

        # Step 1: Check if the Oracle database instance is running
        $instanceStatus = Exec-SqlInContainer -containerName $containerName -sqlCommand "select instance_name, status from v\$instance;"

        # Step 2: Parse the instance status
        if ($instanceStatus -match "OPEN") {
            Write-Output "Oracle database instance is already running."
        } else {
            Write-Output "Starting the Oracle database instance..."
            Exec-SqlInContainer -containerName $containerName -sqlCommand "startup;"
            Write-Output "Oracle database instance started."
        }

        # Step 3: Manually register the database with the listener
        Write-Output "Registering the database with the listener..."
        Exec-SqlInContainer -containerName $containerName -sqlCommand "alter system register;"

        # Step 4: Check the listener status
        $listenerStatus = docker exec -it $containerName lsnrctl status

        Write-Output "Listener Status:"
        Write-Output $listenerStatus
        