name: Docker Register Oracle Service

runs:
  using: 'composite'
  
  steps:
    - name: Register Oracle Service
      shell: pwsh
      run: |
        # Script (Register Oracle Service)
        docker exec oracle-db lsnrctl status
        # Start-Sleep -Seconds 60
        # docker exec oracle-db lsnrctl status
