name: Docker Register Oracle Service

runs:
  using: 'composite'
  
  steps:
    - name: Register Oracle Service
      shell: pwsh
      run: |
        # Script (Register Oracle Service)
        $containerName = "your_oracle_container"
        $services = @("listener", "database")

        # Function to check if a service is running
        function Test-Service {
            param (
                [string]$serviceName
            )
            $status = docker exec $containerName bash -c "ps -ef | grep $serviceName | grep -v grep"
            return $status -ne ""
        }

        # Wait for all services to be ready
        foreach ($service in $services) {
            Write-Host "Waiting for $service to be ready..."
            while (-not (Test-Service -serviceName $service)) {
                Start-Sleep -Seconds 5
            }
            Write-Host "$service is ready."
        }

        Write-Host "All services are ready."
