name: Docker Inspect (Health Check - DB Containers)

runs:
  using: 'composite'
  
  steps:
    - name: Docker Inspect (Wait Status -> Healthy)
      shell: pwsh
      run: |
        # Script (Wait Status -> Healthy)
        $oracleHealth=""
        $msSQLHealth=""
        $mySQLHealth=""
        $status="healthy"
        $allHealthy=$false
        $retry=1
        do {
                $oracleHealth = (docker inspect --format="{{json .State.Health.Status}}" oracle-db).Replace('"', '')
                $msSQLHealth = (docker inspect --format="{{json .State.Health.Status}}" mssql-db).Replace('"', '')
                $mySQLHealth = (docker inspect --format="{{json .State.Health.Status}}" mysql-db).Replace('"', '')
                if (($oracleHealth -ne $status) -or ($msSQLHealth -ne $status) -or ($mySQLHealth -ne $status)) {
                    Start-Sleep -Seconds 10
                    $retry ++
                } else {
                    $allHealthy=$true
                    break
                }
        } while ($retry -le 6)
        if ($allHealthy -eq $true) {
            Write-Host "All DB Containers Healthy ==> [ oracle-db (Status) -> '$oracleHealth' ] | [ mssql-db (Status) -> '$msSQLHealth' ] | [ mysql-db (Status) -> '$mySQLHealth' ]"
        } else {
            Write-Host "DB Container/s Not Healthy ==> [ oracle-db (Status) -> '$oracleHealth' ] | [ mssql-db (Status) -> '$msSQLHealth' ] | [ mysql-db (Status) -> '$mySQLHealth' ]"
            exit 1
        }

    - name: Register Oracle Service
      shell: pwsh
      run: |
        # Script (Register Oracle Service)
        function Check-ServiceName {
          $services = docker exec oracle-db lsnrctl services
          return $services -match "XE"
        }

        $registerCommand = @"
        sqlplus / as sysdba <<EOF
        ALTER SYSTEM REGISTER;
        EXIT;
        EOF
        "@

        $maxRetries = 6
        $retryInterval = 10
        $retryCount = 0
        
        if (-not (Check-ServiceName)) {
          Write-Output "Service name ORCLCDB not found. Registering the service..."
          docker exec oracle-db bash -c "$registerCommand"
          while (-not (Check-ServiceName) -and $retryCount -lt $maxRetries) {
            Write-Output "Waiting for service name ORCLCDB to be registered... (Attempt $($retryCount + 1) of $maxRetries)"
            Start-Sleep -Seconds $retryInterval
            $retryCount++
          }

          if (-not (Check-ServiceName)) {
            Write-Output "Service name ORCLCDB still not found after $maxRetries attempts. Please check the Oracle configuration."
            Write-Output "Checking listener status..."
            docker exec oracle-db lsnrctl status

            Write-Output "Attempting manual registration..."
            docker exec oracle-db bash -c "$registerCommand"

            Write-Output "Checking Oracle logs..."
            docker exec oracle-db bash -c "cat /opt/oracle/diag/alert*.log"
            exit 1
          }
        }
        Write-Output "Oracle container is ready to receive SQL commands."
        