name: Docker Inspect (Health Check - DB Containers)

runs:
  using: 'composite'
  
  steps:
    - name: Docker Inspect (Wait Status -> Healthy)
      shell: pwsh
      run: |
        # Script (Wait Status -> Healthy)
        $oracleHealth=""
        $msSQLHealth=""
        $mySQLHealth=""
        $status="healthy"
        $allHealthy=$false
        $retry=1
        do {
                $oracleHealth = (docker inspect --format="{{json .State.Health.Status}}" oracle-db).Replace('"', '')
                $msSQLHealth = (docker inspect --format="{{json .State.Health.Status}}" mssql-db).Replace('"', '')
                $mySQLHealth = (docker inspect --format="{{json .State.Health.Status}}" mysql-db).Replace('"', '')
                if (($oracleHealth -ne $status) -or ($msSQLHealth -ne $status) -or ($mySQLHealth -ne $status)) {
                    Start-Sleep -Seconds 10
                    $retry ++
                } else {
                    $allHealthy=$true
                    break
                }
        } while ($retry -le 6)
        if ($allHealthy -eq $true) {
            Write-Host "All DB Containers Healthy ==> [ oracle-db (Status) -> '$oracleHealth' ] | [ mssql-db (Status) -> '$msSQLHealth' ] | [ mysql-db (Status) -> '$mySQLHealth' ]"
        } else {
            Write-Host "DB Container/s Not Healthy ==> [ oracle-db (Status) -> '$oracleHealth' ] | [ mssql-db (Status) -> '$msSQLHealth' ] | [ mysql-db (Status) -> '$mySQLHealth' ]"
            exit 1
        }

    - name: Register Oracle Service
      shell: pwsh
      run: |
        function Check-ServiceName {
          $services = docker exec -it oracle-db lsnrctl services
          return $services -match "ORCLCDB"
        }
        if (-not (Check-ServiceName)) {
          Write-Output "Service name ORCLCDB not found. Registering the service..."
          docker exec -it oracle-db sqlplus / as sysdba -c "ALTER SYSTEM REGISTER;"
          Start-Sleep -Seconds 10
          if (-not (Check-ServiceName)) {
            Write-Output "Service name ORCLCDB still not found. Please check the Oracle configuration."
            exit 1
          }
        }
        Write-Output "Oracle container is ready to receive SQL commands."
        