services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      ORACLE_PWD: "Secret1234"
    ports:
      - "1521:1521"
    volumes:
      - ./QueryDB.Core.Tests/SeedData:/home
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s sys/$$ORACLE_PWD@localhost:1521/ORCLCDB as sysdba"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s

  mssql-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secret1234"
    ports:
      - "1433:1433"
    volumes:
      - ./QueryDB.Core.Tests/SeedData:/home
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $$SA_PASSWORD -Q \"SELECT 1\""]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s

  mysql-db:
    image: mysql:8.0.31
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "Secret1234"
    ports:
      - "3306:3306"
    volumes:
      - ./QueryDB.Core.Tests/SeedData:/home
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost --silent"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s
      