version: "3"
services:

  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      ORACLE_PWD: "Secret@1234"
    ports:
      - "1521:1521"

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sql-server-db
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Secret@1234"
    ports:
      - "1433:1433"

  mysql-db:
    image: mysql:8.0.31
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: "Secret@1234"
    ports:
      - "3306:3306"