services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    environment:
      ORACLE_PWD: "Secret@1234"
    ports:
      - "1521:1521"
    volumes:
      - ./QueryDB.Core.Tests/SeedData:/home
    healthcheck:
      test: ["CMD-SHELL", "echo 'SELECT 1 FROM DUAL;' | sqlplus -s sys/$$ORACLE_PWD@localhost:1521/ORCLCDB as sysdba"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 0s
