name: Docker Execute (Seed Data)

runs:
  using: 'composite'
  
  steps:
    - name: Docker Execute (ORACLE - Seed Data)
      shell: bash
      run: |
        echo $ORACLE_PWD
        docker exec oracle-db bash -c "sqlplus -s sys/$ORACLE_PWD@localhost:1521/XE as sysdba @/home/oracle.sql"
      env:
        ORACLE_PWD: "Secret1234"

    - name: Docker Execute (MSSQL - Seed Data)
      shell: bash
      run: |
        docker exec mssql-db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Secret@1234 -i "/home/mssql.sql"

    - name: Docker Execute (MYSQL - Seed Data)
      shell: bash
      run: |
        docker exec mysql-db mysql -uroot -pSecret@1234 -e "source /home/mysql.sql"
