name: Docker Execute (Seed Data)

inputs:
  dbPassword:
    description: 'Database password value.'
    required: true

runs:
  using: 'composite'
  
  steps:
    - name: Docker Execute (MSSQL - Seed Data)
      shell: bash
      run: |
        docker exec mssql-db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $MSSQL_PWD -i "/home/mssql.sql"
      env:
        MSSQL_PWD: ${{ inputs.dbPassword }}

    - name: Docker Execute (MYSQL - Seed Data)
      shell: bash
      run: |
        docker exec mysql-db mysql -uroot -p$MYSQL_PWD -e "source /home/mysql.sql"
      env:
        MYSQL_PWD: ${{ inputs.dbPassword }}

    - name: Docker Execute (ORACLE - Seed Data)
      shell: bash
      run: |
        docker exec oracle-db bash -c "sqlplus -s sys/$ORACLE_PWD@localhost:1521/XE as sysdba @/home/oracle.sql"
        docker exec oracle-db bash -c "echo \"SELECT BFILE_COLUMN FROM DataTypes;\" | sqlplus -s sys/$ORACLE_PWD@localhost:1521/XE as sysdba"
        docker exec oracle-db bash -c "echo \"SELECT DIRECTORY_NAME, DIRECTORY_PATH FROM ALL_DIRECTORIES WHERE DIRECTORY_NAME = 'MY_DIRECTORY';\" | sqlplus -s sys/$ORACLE_PWD@localhost:1521/XE as sysdba"
        docker exec oracle-db bash -c "echo \"SELECT DIRECTORY_NAME, DIRECTORY_PATH FROM ALL_DIRECTORIES WHERE DIRECTORY_NAME = 'my_directory';\" | sqlplus -s sys/$ORACLE_PWD@localhost:1521/XE as sysdba"
        docker exec oracle-db bash -c "ls -l /home"
        docker exec oracle-db bash -c "ls /home/oracle.sql"
      env:
        ORACLE_PWD: ${{ inputs.dbPassword }}

    - name: Docker Execute (POSTGRESQL - Seed Data)
      shell: bash
      run: |
        docker exec postgres-db bash -c "PGPASSWORD=$POSTGRESQL_PWD psql -d postgres -U sys -f /home/postgresql.sql"
      env:
        POSTGRESQL_PWD: ${{ inputs.dbPassword }}
