name: Docker Execute (Seed Data)

runs:
  using: 'composite'
  
  steps:
    - name: Docker Execute (ORACLE - Seed Data)
      shell: bash
      run: |
        docker exec -i oracle-db bash -c "echo @/home/oracle.sql | sqlplus -s sys/Secret@1234@localhost:1521/ORCLCDB as sysdba"

    - name: Docker Execute (MSSQL - Seed Data)
      shell: bash
      run: |
        docker exec mssql-db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Secret@1234 -i "/home/mssql.sql"

    - name: Docker Execute (MYSQL - Seed Data)
      shell: bash
      run: |
        docker exec mysql-db mysql -uroot -pSecret@1234 -e "source /home/mysql.sql"
