name: Docker Execute (Seed Data)

runs:
  using: 'composite'
  
  steps:
    - name: Docker Execute (ORACLE - Seed Data)
      shell: bash
      run: |
        docker exec oracle-db bash -c "sqlplus -s sys/$ORACLE_PASSWORD@localhost:1521/XE as sysdba @/home/oracle.sql"
      env:
        ORACLE_PASSWORD: "Secret1234"

    - name: Docker Execute (MSSQL - Seed Data)
      shell: bash
      run: |
        docker exec mssql-db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $MSSQL_PASSWORD -i "/home/mssql.sql"
      env:
        MSSQL_PASSWORD: "Secret1234"

    - name: Docker Execute (MYSQL - Seed Data)
      shell: bash
      run: |
        docker exec mysql-db mysql -uroot -p$MYSQL_PASSWORD -e "source /home/mysql.sql"
      env:
        MYSQL_PASSWORD: "Secret1234"
