name: Docker Execute (Seed Data)

runs:
  using: 'composite'
  
  steps:
    - name: Docker Execute (ORACLE - Seed Data)
      shell: bash
      run: |
        echo $ORACLE_PWD
        docker exec oracle-db bash -c "sqlplus -s sys/$ORACLE_PWD@localhost:1521/XE as sysdba @/home/oracle.sql"
      env:
        ORACLE_PWD: ${{ secrets.DB_PASSWORD }}

    - name: Docker Execute (MSSQL - Seed Data)
      shell: bash
      run: |
        docker exec mssql-db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $MSSQL_PWD -i "/home/mssql.sql"
      env:
        MSSQL_PWD: ${{ secrets.DB_PASSWORD }}

    - name: Docker Execute (MYSQL - Seed Data)
      shell: bash
      run: |
        docker exec mysql-db mysql -uroot -p$MYSQL_PWD -e "source /home/mysql.sql"
      env:
        MYSQL_PWD: ${{ secrets.DB_PASSWORD }}
