name: Docker Compose (Start - DB Containers)

inputs:
  dbPassword:
    description: 'Database password value.'
    required: true

runs:
  using: 'composite'
  
  steps:
    - name: Find And Replace Values (Docker Compose)
      uses: abhinavminhas/replace-tokens@main
      with:
        files: '${{ github.workspace }}/docker-compose.yml'
        replacements: '__DB_PASSWORD__=${{ inputs.dbPassword }},__DB_PASSWORD__=${{ inputs.dbPassword }},__DB_PASSWORD__=${{ inputs.dbPassword }},__DB_PASSWORD__=${{ inputs.dbPassword }}'

    - name: Docker Compose (Pull)
      shell: bash
      run: docker compose -f docker-compose.yml pull --parallel

    - name: Docker Compose (Start - DB Containers)
      shell: bash
      run: docker compose -f docker-compose.yml up -d
      