#CI/MANUAL TRIGGER
name: Build

on:
  push:
    branches: [ main, dev ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Build/Test
  OS-NetCore:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04, macOS-12 ]
        dotnet-version: [ '3.1.x', '6.0.x', '7.0.x', '8.0.x' ]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dotnet Version (${{ matrix.dotnet-version }})
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    
    - name: Find And Replace Values (App Config)
      uses: abhinavminhas/replace-tokens@main
      with:
        files: '${{ github.workspace }}/QueryDB.Core.Tests/App.config'
        replacements: '__DB_PASSWORD__=${{ secrets.DB_PASSWORD }}'
        
    - name: Build
      run: dotnet build QueryDB.Core.Tests/QueryDB.Core.Tests.csproj --configuration Release

    - name: Docker Compose (Start - DB Containers)
      if: ${{ (matrix.os == 'ubuntu-20.04') && (matrix.dotnet-version == '3.1.x') }}
      uses: ./.github/workflows/docker-compose-start-dbs
      with:
        dbPassword: ${{ secrets.DB_PASSWORD }}
    
    - name: Docker Execute (Seed Data)
      if: ${{ (matrix.os == 'ubuntu-20.04') && (matrix.dotnet-version == '3.1.x') }}
      uses: ./.github/workflows/docker-execute-seed-data
      with:
        dbPassword: ${{ secrets.DB_PASSWORD }}
    
    - name: Test
      if: ${{ (matrix.os == 'ubuntu-20.04') && (matrix.dotnet-version == '3.1.x') }}
      run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory=DB-TESTS
    
    - name: Docker Compose (Tear Down - DB Containers)
      if: ${{ (matrix.os == 'ubuntu-20.04') && (matrix.dotnet-version == '3.1.x') }}
      uses: ./.github/workflows/docker-compose-teardown-dbs

  # Code Coverage
  Code-Coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dotnet-version: [ '3.1.x' ]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dotnet Version (${{ matrix.dotnet-version }})
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Find And Replace Values (App Config)
      uses: abhinavminhas/replace-tokens@main
      with:
        files: '${{ github.workspace }}/QueryDB.Core.Tests/App.config'
        replacements: '__DB_PASSWORD__=${{ secrets.DB_PASSWORD }}'
        
    - name: Build
      run: dotnet build QueryDB.Core.Tests/QueryDB.Core.Tests.csproj --configuration Release

    - name: Docker Compose (Start - DB Containers)
      uses: ./.github/workflows/docker-compose-start-dbs
      with:
        dbPassword: ${{ secrets.DB_PASSWORD }}

    - name: Docker Execute (Seed Data)
      uses: ./.github/workflows/docker-execute-seed-data
      with:
        dbPassword: ${{ secrets.DB_PASSWORD }}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory=DB-TESTS /p:CollectCoverage=true /p:CoverletOutputFormat=lcov

    - name: Docker Compose (Tear Down - DB Containers)
      uses: ./.github/workflows/docker-compose-teardown-dbs

    - name: Upload Coverage To Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
