name: Code Coverage

on:
  workflow_dispatch:

jobs:
  Code-Coverage:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        dotnet-version: [ '3.1.x' ]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Dotnet Version (${{ matrix.dotnet-version }})
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build
      run: dotnet build QueryDB.Core.Tests/QueryDB.Core.Tests.csproj --configuration Release

    - name: Docker Compose (Pull)
      run: docker compose -f docker-compose.yml pull --parallel

    - name: Docker Compose (Start - DB Containers)
      run: docker compose -f docker-compose.yml up -d

    - name: Docker Inspect (Wait Status -> Healthy)
      shell: pwsh
      run: |
        # Script (Wait Status -> Healthy)
        $oracleHealth=""
        $msSQLHealth=""
        $mySQLHealth=""
        $status="healthy"
        $allHealthy=$false
        $retry=1
        do {
                $oracleHealth = (docker inspect --format="{{json .State.Health.Status}}" oracle-db).Replace('"', '')
                $msSQLHealth = (docker inspect --format="{{json .State.Health.Status}}" mssql-db).Replace('"', '')
                $mySQLHealth = (docker inspect --format="{{json .State.Health.Status}}" mysql-db).Replace('"', '')
                if (($mySQLHealth -ne $status) -or ($msSQLHealth -ne $status) -or ($oracleHealth -ne $status)) {
                    Start-Sleep -Seconds 10
                    $retry ++
                } else {
                    $allHealthy=$true
                    break
                }
        } while ($retry -le 6)
        if ($allHealthy -eq $true) {
            Write-Host "All DB Containers Healthy ==> [ oracle-db (Status) -> '$oracleHealth' ] | [ mssql-db (Status) -> '$msSQLHealth' ] | [ mysql-db (Status) -> '$mySQLHealth' ]"
        } else {
            Write-Host "DB Container/s Not Healthy ==> [ oracle-db (Status) -> '$oracleHealth' ] | [ mssql-db (Status) -> '$msSQLHealth' ] | [ mysql-db (Status) -> '$mySQLHealth' ]"
            exit 1
        }
    
    - name: Docker Execute (Seed Data)
      shell: pwsh
      run: |
        docker exec -it sql-server-db /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P Secret@1234 -i "/home/mssql.sql"
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --filter TestCategory=DB-TESTS /p:CollectCoverage=true /p:CoverletOutputFormat=lcov
    
    - name: Docker Compose (Tear Down - DB Containers)
      run: docker compose -f docker-compose.yml down

    - name: Upload Coverage To Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
